name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        echo "Deploying to GitHub Pages..."
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Automated deployment"
          git push origin main
        else
          echo "No changes to commit"
        fi